name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Build Rust Benchmark
        run: cargo build --release && cd benchmark/rust && cargo build --release

      - name: Run benchmarks
        run: ./benchmark/run_benchmark.sh

      - uses: blacha/hyperfine-action@v1
        with:
          # Configuration file to use
          benchmark-config: ".hyperfine.json"
          # Number of benchmarks to keep
          count: 100
          # Branch to use for benchmarks output/benchmark.json
          benchmark-branch: "gh-pages"
          # Where to store the output of the benchmarks
          benchmark-output: "benchmarks.json"
          # benchmark html file to view the benchmarks
          benchmark-html: "benchmarks.html"
          # Branch to use as the main or master for comparision
          master-branch: "master"
          # configuration token
          github-token: ${{ github.token }}
